swagger: "2.0"
info:
  version: "0.1.0"
  title: "Offhook agent API"
paths:
  -
definitions:
  DownloadSpec:
    type: "object"
    #required:
    properties:
      source:
        type: "string"
        format: "yum"
      os:
        type: "string"
        format: "linux"
      osVariant:
        type: "string"
        format: "RHEL7"
      architecture:
        type: "string"
        format: "x86_64"
      packages:
        type: "array"
        items:
          type: "string"
          example: "gcc"
  DownloadRequest:
    type: "object"
    #required:
    properties:
      id:
        type: "integer"
        format: "int64"
      spec:
        $ref: "#/definitions/DownloadSpec"
