swagger: "2.0"
info:
  version: "0.1.0"
  title: "Offhook agent API"
paths:
  /search:
    post:
      tags:
      - "Search"
      summary: "Search for packages"
      operationId: "search"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/DownloadSpec"
      responses:
        200:
          description: "Successful search"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/SearchResult"

  /download:
    post:
      tags:
      - "Downloads"
      summary: "Submit a download request"
      operationId: "submit-download-request"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/DownloadSpec"
      responses:
        200:
          description: "Successfully submitted the download request"
          schema:
            $ref: "#/definitions/DownloadRequest"

  /download/{requestId}:
    get:
      tags:
      - "Downloads"
      summary: "Get a download request"
      operationId: "get-download-request"
      produces:
      - "application/json"
      parameters:
      - name: "requestId"
        in: "path"
        description: "ID of request to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Successfully returned"
          schema:
            $ref: "#/definitions/DownloadRequest"
        404:
          description: "Request with the given ID was not found"

  /download/{requestId}/files:
    get:
      tags:
      - "Downloads"
      summary: "Get files from a download request"
      operationId: "get-download-files"
      produces:
      - "application/x-7z-compressed"
      parameters:
      - name: "requestId"
        in: "path"
        description: "ID of request to get the files for"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "A compressed file containing the downloaded packages"
          schema:
            type: file
        400:
          description: "The files for the specified request are not ready"
        404:
          description: "Request with the given ID was not found"

definitions:
  DownloadSpec:
    type: "object"
    required:
    - "source"
    - "os"
    - "packages"
    properties:
      source:
        type: "string"
        example: "yum"
      os:
        type: "string"
        example: "el7"
      architecture:
        type: "string"
        example: "x86_64"
      packages:
        type: "array"
        items:
          type: "string"
          description: "Package name or full name"
        example:
        - "gcc"
        - "gcc-0:4.8.5-39.el7.x86_64"

  DownloadRequest:
    type: "object"
    required:
    - "id"
    - "spec"
    - "status"
    - "isConsumable"
    properties:
      id:
        type: "integer"
        format: "int64"
      spec:
        $ref: "#/definitions/DownloadSpec"
      status:
        type: "string"
        description: |
          Request status to display for the user.
          CAUTION: Do not rely on this for any computation!
      isConsumable:
        type: "boolean"
        description: "Whether the requested files are ready for download or not"
      compressedFileType:
        type: "string"
        description: "The file type to compress the packages into"
        enum:
        - "7z"
        default: "7z"

  SearchResult:
    type: "object"
    required:
    - "name"
    - "fullName"
    properties:
      name:
        type: "string"
        example: "gcc"
      fullName:
        type: "string"
        example: "gcc-0:4.8.5-39.el7.x86_64"
        description: "A fully-describing name of the package"
