swagger: "2.0"
info:
  version: "0.1.0"
  title: "Offhook agent API"
paths:
  /search:
    post:
      tags:
      - "Search"
      summary: "Search for packages"
      operationId: "search"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/DownloadSpec"
      responses:
        200:
          description: "Successful search"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/SearchResults"

  /download:
    post:
      tags:
      - "Downloads"
      summary: "Submit a download request"
      operationId: "submit-download-request"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/DownloadSpec"
      responses:
        200:
          description: "Successfully submitted the download request"
          schema:
            $ref: "#/definitions/DownloadRequest"

  /download/{requestId}:
    get:
      tags:
      - "Downloads"
      summary: "Get a download request"
      operationId: "get-download-request"
      produces:
      - "application/json"
      parameters:
      - name: "requestId"
        in: "path"
        description: "ID of request to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Successfully returned"
          schema:
            $ref: "#/definitions/DownloadRequest"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Request with the given ID was not found"

definitions:
  DownloadSpec:
    type: "object"
    required:
    - "source"
    - "os"
    - "packages"
    properties:
      source:
        type: "string"
        example: "yum"
      os:
        type: "string"
        example: "linux"
      osVariant:
        type: "string"
        example: "RHEL7"
      architecture:
        type: "string"
        example: "x86_64"
      packages:
        type: "array"
        items:
          type: "string"
          example:
          - "gcc"
          - "gcc-0:4.8.5-39.el7.x86_64"
          description: "Package name or NEVRA"

  DownloadRequest:
    type: "object"
    required:
    - "id"
    - "spec"
    - "status"
    properties:
      id:
        type: "integer"
        format: "int64"
      spec:
        $ref: "#/definitions/DownloadSpec"
      status:
        type: "string"
        enum:
        - "submitted"
        - "downloading"
        - "packaging"
        - "done"

  SearchResult:
    type: "object"
    required:
    - "name"
    - "nevraString"
    properties:
      name:
        type: "string"
        example: "gcc"
      nevraString:
        type: "string"
        example: "gcc-0:4.8.5-39.el7.x86_64"
        description: "NEVRA (Name, Epoch, Version, Revision, Architecture) of the package"

  SearchResults:
    type: "object"
    required:
    - "results"
    properties:
      results:
        type: "array"
        items:
          $ref: "#/definitions/SearchResult"
